name: ESLint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "35 8 * * 2"

jobs:
  lint:
    name: Run lint & audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install & run ESLint + audit
        run: |
          pnpm install --frozen-lockfile
          # keep the env used by your ESLint SARIF exporter if needed
          SARIF_ESLINT_IGNORE_SUPPRESSED="true" pnpm lint
          # run audit without installing globally
          pnpm dlx better-npm-audit --level high
